filter:
  paths:
    - src/

build:
  environment:
    php: 7.1


  tests:
    before:
      - 'bin/nxscli da:ge'
    override:
      -
        command: 'vendor/bin/codecept run --coverage --coverage-xml'
        coverage:
          file: 'tests/_output/coverage.xml'
          format: 'clover'

checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true