build:
    environment:
        php: '7.1'
        node: '8.10.0'
    dependencies:
        before:
            - 'rm -rf ./node_modules'
            - 'npm cache -f clear'
            - 'composer remove --dev spryker/git-hook'

    tests:
        override:
            -
              command: 'vendor/bin/codecept run --coverage --coverage-xml'
              coverage:
                file: 'tests/_output/coverage.xml'
                format: 'clover'