filter:
  paths:
    - "src/"

  excluded_paths:
    - "tests/"

  dependency_paths:
    - "vendor/"

build:
  environment:
    php: '7.1'

  nodes:
    analysis:
      tests:
        override:
          -
            command: 'vendor/bin/codecept run --coverage --coverage-xml'
            coverage:
              file: 'tests/_output/coverage.xml'
              format: 'clover'