build:
    environment:
        php: '7.1'

    filter:
        dependency_paths: ["tests/_support/_generated/*"]

    tests:
        override:
            -
              command: 'vendor/bin/codecept run --coverage --coverage-xml'
              coverage:
                file: 'tests/_output/coverage.xml'
                format: 'clover'